# Generated by Django 3.0.3 on 2020-02-29 17:38

import datetime
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200220_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='item',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 29, 9, 37, 55, 62197)),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='images/no_image.png', upload_to='images', validators=[products.models.Item.validate_image]),
        ),
    ]
